language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - ruby-head
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx
#  - jruby-head

# whitelist
branches:
  only:
    - master
    - develop

matrix:
  allow_failures:
    - rvm: ruby-head
#    - rvm: jruby-head
#    - rvm: rbx